* niteLite.io

Personal blog powered by Wintersmith static site generator

** Requirements

Be sure to have [[http://nodejs.org/download/][Node Package Manager (npm)]] installed. Npm is bundled and
installed automatically with NodeJS. [[https://www.ruby-lang.org/en/downloads/][Ruby 2.0.0]] is needed as well.

** Setup

Setting up a buildable project is very simple:

#+begin_src sh
git clone https://github.com/hackbytes/nitelite.io.git
cd nitelite.io
./init.sh
#+end_src

Once all necessary dependencies have been installed by the init command,
you can open up the project in your preferred editor and run builds, perform
unit tests or anything else!

** Usage

You can use your favorite IDE to run all builds and unit tests. If you prefer
to use the command line, you can use grunt tasks to run builds and test the
application.

The following is a list of all available commands. Execute whichever command
you need.

To build the website:

#+begin_src sh
grunt build
#+end_src

To build and run both the website and all tests:

#+begin_src sh
grunt test
#+end_src

To build the tests without running them:

#+begin_src sh
grunt build-tests
#+end_src

To run the tests without building them (this assumes you have previously built
them):

#+begin_src sh
grunt run-tests
#+end_src

To clean all built files:

#+begin_src sh
grunt clean
#+end_src

To deploy the website to the server:

#+begin_src sh
grunt deploy
#+end_src

To bulk update the YAML front-matter of every post

#+begin_src sh
grunt yaml:key:value
#+end_src

To view posts that can be unpublished. Specify a skill or a notebook to narrow 
down the list.

#+begin_src sh
grunt publish[:skill][:notebook]
#+end_src

To publish a post

#+begin_src sh
grunt publish:skill:notebook:post
#+end_src

To view posts that can be unpublished. Specify a skill or a notebook to narrow 
down the list.

#+begin_src sh
grunt publish[:skill][:notebook]
#+end_src

To unpublish a post

#+begin_src sh
grunt unpublish:skill:notebook:post
#+end_src

** Comments

The comments database is created upon submission of the first comment. The
following is a list of all available commands for managing comments once the
database is created.

To pull the comments database from the server:

#+begin_src sh
grunt comments-pull
#+end_src

To display a list of all comments along with their ids:

#+begin_src sh
grunt comments-list
#+end_src

To view the contents of a comment:

#+begin_src sh
grunt comments-view:id
#+end_src

To publish a comment:

#+begin_src sh
grunt comments-publish:id
#+end_src

To unpublish a comment:

#+begin_src sh
grunt comments-unpublish:id
#+end_src

To delete a comment:

#+begin_src sh
grunt comments-delete:id
#+end_src

To push the modified database back to the server:

#+begin_src sh
grunt comments-push
#+end_src

** Copyright / License

niteLite.io is Copyright (c) 2014 niteLite.io, licensed under the GNU GPL 
v2.0.

This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, version 2 of the License.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program. If not, see <http://www.gnu.org/licenses/>.

niteLite.io includes works under other copyright notices and distributed
according to the terms of the GNU General Public License or a compatible
license, including:

  TODO

