language: node_js
node_js:
  - 0.10
cache:
  bundler: true
  directories:
    - node_modules
    - bower_components
    - vendor/bundle
before_install:
  - rvm install $RVM_RUBY_VERSION
  - rvm use $RVM_RUBY_VERSION
install:
  - ./init.sh
script: true
env:
  - RVM_RUBY_VERSION=2.0.0

